### ISSUE TITLE
Can anyone explain the timeline switcher code to me???

### ISSUE THREAD

**Issue by dsheeler** [dsheeler/CoverflowAltTab#210]
It has problems, but I can't wrap my head around how it works. @machitgarha @dmo60 @p91paul any of you guys ever understand it? If so, maybe you can explain it to me?

**Comment by dmo60** [comment]
I can't, it's been too long since I was involved in actual coding here. Sorry.

**Comment by p91paul** [comment]
Sorry, I think only basic maintenance happened on that code since @Lusito contributed it 10 years ago...

**Comment by machitgarha** [comment]
Sorry for the late reply, but is it still a problem?

**Comment by dsheeler** [comment]
I got this figured out, pretty much!
