### ISSUE TITLE
Gnome 46.alpha

### ISSUE THREAD

**Issue by nater1983** [dsheeler/CoverflowAltTab#213]
I have tested this extension so far today on Gnome 46.alpha by adding in 46 to the shell numbers and it looks like the Alt+Tab mite not be working correctly. Just an fyi.

Slackware Current
Gnome Shell 46.Alpha

**Comment by dsheeler** [comment]
I have no idea what's coming. Switch to 45 was pretty big, so I hope this isn't too big!

**Comment by nater1983** [comment]
I am with you I will keep you updated as I compile more of Gnome 46 for Slackware.

**Comment by nater1983** [comment]
bind to switch-windows is working but bind to switch-applications is not so far on version 70 with shell 46

**Comment by dsheeler** [comment]
@nater1983, I just made https://github.com/dmo60/CoverflowAltTab/tree/213-gnome-46alpha for porting to 46.  It might be working in 46. Could you try it out, too? My testing environment is flaky (I can't change settings, don't know why, but the settings window never displays).

**Comment by nater1983** [comment]
![image](https://github.com/dmo60/CoverflowAltTab/assets/46272571/ac8a26ce-c6a9-412a-a990-3efd2770a5d2)
![image](https://github.com/dmo60/CoverflowAltTab/assets/46272571/6e4c297b-1998-4298-9f18-ef7e509dbbb6)

**Comment by nater1983** [comment]
This is on a fully updated Slackware Current System with all Gnome 46 Components. As well as glib 2.79.0 a899933acbced812355528fb62d82283fe6dae47
and gjs 1.79.2

**Comment by dsheeler** [comment]
Are the windows rotated oddly? Is that what you're showing with the images?

**Comment by nater1983** [comment]
Na I am just trying to show that using alt-tab is working now. :)

**Comment by dsheeler** [comment]
Wonderful!!! Thanks for trying so quickly!

**Comment by dsheeler** [comment]
Also good to know prefs don't work for you. I just tried to look for an error with journalctl and the prefs window coredumps, but I can't figure out why by looking at it. Betting there's a change that just affects prefs, but we'll see!

**Comment by nater1983** [comment]
![image](https://github.com/dmo60/CoverflowAltTab/assets/46272571/ace6bffd-87d3-41aa-b9b6-1fc70241eb4e)

**Comment by dsheeler** [comment]
Did it just work for you?

**Comment by nater1983** [comment]
The settings have always worked for me. Even when the alt-tab funtion wasnt working.

**Comment by dsheeler** [comment]
Oh, sorry misread your earlier post! Hmm, well, that's good. I'm running GnomeOS in Boxes. No idea why settings are crashing here

**Comment by nater1983** [comment]
humm now I kinda want to see what your seeing.....

**Comment by dsheeler** [comment]
Oh cool!

**Comment by nater1983** [comment]
Still works without problems in 46.beta

**Comment by rudrab** [comment]
It seems this is freezing the tab..i.e. runs over all the link on a webpage or tabs on the editor(gvim).
I have installed it from gnome-extension website.
I am in fedora40, gnome 46.

I reported the issue here so that the gnome46 related topics are in one place. Hope that is OK.

**Comment by rudrab** [comment]
@dsheeler I was trying that...but since the event is random, I haven't managed a screencast yet. Is there any other way (e.g, dmesg output) to show the event?

**Comment by dsheeler** [comment]
@rudrab, while I'm developing the extension, if I encounter an issue like a crash or a freeze while using, I eventually get to a terminal and run:

`journalctl -rb /usr/bin/gnome-shell`

and search that output for 'Coverflow' to find error messages (the -r means newest messages first, and -b just limits log to events since last boot). 

So if this randomly happens, maybe try that. 

But so what happens exactly? You are pressing alt-tab but at some point the tab affects a specific window?
