### ISSUE TITLE
Scroll with mouse kinda broken

### ISSUE THREAD

**Issue by Cobeta-beta** [dsheeler/CoverflowAltTab#221]
When you try to scroll between tabs with mouse, it skips two, instead of one. afaik, (as far as I know) you cant change it.

**Comment by dsheeler** [comment]
Thank you for reporting!  I have the same experience with the mouse scrolling. I'll work on this right now.

**Comment by Cobeta-beta** [comment]
thanks! :>
(Btw, i'm working on Ukraine, and Russian translations!)

**Comment by dsheeler** [comment]
That's awesome!  Thank you!

**Comment by dsheeler** [comment]
@Cobeta-beta, I made the mousewheel work by a totally different mechanism. Now it's more like a swipe.  Tell me what you think! I'm about to merge it into the [gnome-45](https://github.com/dsheeler/CoverflowAltTab/tree/gnome-45) branch (and the main branch which only runs on 46).
