### ISSUE TITLE
[FEATURES REQUEST] WINDOW VALIDATION

### ISSUE THREAD

**Issue by JE-Amouel** [dsheeler/CoverflowAltTab#258]
Hi,
firstly, thanks for adding the dbus functionality,

I was able to improve my script, and trigger coverflow properly,

I was able to easily interface it at the AATWS dock

and also on CHC, which was now in the top right corner of my screen, I was able to define two actions:
scroll up: overview of activities
scroll down: coverflow - window switcher

and all that without torturing my fingers too much with the usual keyboard shortcuts.

however I still have a suggestive request to improve the interface which is triggered by the Dbus method, all this boils down to the selection of windows, relative to navigation by keyboard and/or mouse.

the current behavior is that when I navigate between windows, to be able to select a window, I must be above it, and press ESC, which I find a little counter-intuitive.

I think it would still be nice to be able to have the possibility of not choosing any window.

with the mouse, for example if I trigger coverflow from my hot corner or the dock, when the Coverflow window switching interface is triggered, I would like to be able to scroll in front of all my windows as needed, and only switch windows if I left click on it, and if I click in the void, I would like to return to the window previously targeted before triggering coverflow.

with the keyboard,
I would like to be able to select the window when I press ENTER,
and exit the interface when I press ESC to return to the previously targeted window.

THANKS

**Comment by dsheeler** [comment]
>  if I click in the void, I would like to return to the window previously targeted before triggering coverflow.

This I will have to work differently, I think. The issue is you can click and drag to switch windows (you might not have discovered this), so clicking into the void activates the drag... maybe it could be a double click or something?

**Comment by dsheeler** [comment]
Maybe if you right click anywhere you exit without picking?

**Comment by dsheeler** [comment]
@JE-Amouel I can do what you want, actually, and support the drag functionality. So get ready to be happier :)

**Comment by JE-Amouel** [comment]
Really sorry for the time it took me to respond,

>Maybe if you right click anywhere you exit without picking?

On this point I trust you, 💯

>I can do what you want, actually, and support the drag functionality. So get ready to be happier :)

I already know that in your hands, the result will be dazzling.✨

**Comment by dsheeler** [comment]
@JE-Amouel check out this branch: https://github.com/dsheeler/CoverflowAltTab/tree/258-features-request-window-validation. As I understand it, it is what you want.

**Comment by JE-Amouel** [comment]
I knew you could do it, :100:
I feel like I'm discovering the extension again, :star: 
and  in addition, all the other integrated options work well,
what a great job, :+1: 

THANKS :pray:

**Comment by dsheeler** [comment]
@JE-Amouel if you haven't found any problems or bugs then I will merge this into the main branch.  I haven't had any problems, myself.

**Comment by JE-Amouel** [comment]
>if you haven't found any problems or bugs then I will merge this into the main branch. I haven't had any problems, myself.

It still work good for me. 

i think we have another enhancement :wink:
