### ISSUE TITLE
Сompatibility with the extension "Blyr"

### ISSUE THREAD

**Issue by boris-gu** [dsheeler/CoverflowAltTab#94]
I use the extension ["blyr",](https://github.com/yozoon/gnome-shell-extension-blyr) but it does not cope with blurring in CoverflowAltTab.
I do not know how this all works, but is it possible to do something about it?
![111](https://user-images.githubusercontent.com/44787162/53121446-583ef200-3565-11e9-9e75-14e519f46f70.png)
"normal behavior" vs "in CoverflowAltTab"

**Comment by p91paul** [comment]
have you tried to contact the blyr maintainers? it's unlikely Coverflow can do something, it's up to them to blur things I suppose!

**Comment by dasnoopy** [comment]
@p91paul  : maybe you could  evaluated the possibility to implement , in the preferences panel, an option  to set blur background as alternative to the background-dim. 

Now,  with gnome shell vers. >= 3.36.x , it is possible have a native support for blurred background.. (https://blogs.gnome.org/shell-dev/2020/02/18/login-and-unlock-in-gnome-shell-3-36).
Also  blyr extension adopted this in the latest version (https://github.com/yozoon/gnome-shell-extension-blyr/commit/6eb7aee909ef5bf683af7d2518825481776c1b2b) ....

Thanks in advance
Andrea

**Comment by dsheeler** [comment]
You can now use the blur-my-shell extension to blur the coverflow background! See that extension's settings to activate it!
